### ISSUE TITLE
Length of a decimal column should be in this format: "8, 2"

### ISSUE THREAD

**Issue by trevburley** [laravel-factory/feature-requests#12]
Length of a decimal column should be in this format: "8, 2"

Appears when clicking 'Update Columns' even when you aren't using decimals. 

Clicking Update Columns a second time then works correctly.

I believe it is due to the length column displaying when you select the column type of 'string', I input the length and then click 'Update Columns'. After the error appears the length column is gone on all text fields and allows you to proceed.

**Comment by gauravmak** [comment]
We just fixed it

**Comment by behrndtt** [comment]
This issue seems to have re-appeared.

**Comment by gauravmak** [comment]
Sorry for that. Fixed now.
